### ISSUE TITLE
Unable to update

### ISSUE THREAD

**Issue by ZentaChainAdmin** [ascjones/subsee#4]
Failed to load source for dependency [`frame-metadata`](https://github.com/paritytech/frame-metadata?branch=subsee#576f9a37)

> Caused by:
  object not found - no match for id (576f9a3756d4cbd9f7165bee3074e024aca2b4d7); class=Odb (9); code=NotFound (-3)

**Comment by ascjones** [comment]
Should be fixed now with https://github.com/ascjones/subsee/commit/5de6a62bd74124807156c4134ca083801ef2059c
